version: "3.8"
services:
  db:
    image: postgis/postgis:15-3.5
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: Nightlife
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: .
    environment:
      DATABASE_URL: postgresql://postgres:password@db:5432/Nightlife?schema=public
    depends_on:
      - db
    ports:
      - "3000:3000"
    command: >
      sh -c "npx prisma migrate dev --name init && npx prisma db seed && npm run start"

volumes:
  pgdata:
